# Generated by Django 4.1.1 on 2022-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_hotel_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('startingtime', models.CharField(max_length=200)),
                ('endingtime', models.CharField(max_length=200)),
                ('bustype', models.CharField(max_length=200)),
                ('count', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagetype', models.CharField(max_length=200)),
                ('packagedetails', models.CharField(max_length=200)),
                ('packagename', models.CharField(max_length=200)),
                ('startingdate', models.DateField(max_length=200)),
                ('endingdate', models.DateField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('image',models.CharField(max_length=2500)),
            ],
        ),
    ]
