# Generated by Django 4.1.1 on 2022-10-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_bus_busname_bus_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bus',
            new_name='Vehicle',
        ),
    ]
