# Generated by Django 4.1.2 on 2022-10-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_bus_vehicle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package',
            table='registration_package',
        ),
    ]
