# Generated by Django 4.1.2 on 2022-10-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_package_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
    ]
