# Generated by Django 4.1.2 on 2022-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
