# Generated by Django 4.1.2 on 2022-10-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_package_image_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
