# Generated by Django 4.1.2 on 2022-10-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_package_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='package',
            new_name='Tourpackages',
        ),
    ]
