# Generated by Django 4.1.2 on 2022-10-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_rename_package_tourpackages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourpackages',
            table=None,
        ),
    ]
