# Generated by Django 4.1.2 on 2022-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
