# Generated by Django 4.1.2 on 2022-10-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_tourpackages_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourpackages',
            new_name='Packagess',
        ),
    ]
