# Generated by Django 4.1.2 on 2022-10-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_rename_tourpackages_packagess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packagess',
            new_name='package',
        ),
    ]
