# Generated by Django 4.1.2 on 2022-10-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_rename_packagess_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available_seats',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='count',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='count',
            field=models.IntegerField(max_length=200),
        ),
        migrations.CreateModel(
            name='Vehicle_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passenger_name', models.CharField(max_length=200)),
                ('Passenger_mobile', models.IntegerField(max_length=10)),
                ('Passenger_email', models.CharField(max_length=200)),
                ('numberof_seats', models.IntegerField(max_length=200)),
                ('adhar_number', models.CharField(max_length=200)),
                ('total_rate', models.IntegerField(max_length=200)),
                ('Bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.vehicle')),
            ],
        ),
    ]
