# Generated by Django 4.1.2 on 2022-10-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_vehicle_available_seats_alter_hotel_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_booking',
            name='adhar_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking',
            name='total_rate',
            field=models.IntegerField(null=True),
        ),
    ]
