# Generated by Django 4.1.2 on 2022-10-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_vehicle_booking_adhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_booking',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.new_user'),
        ),
    ]
