# Generated by Django 4.1.2 on 2022-10-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_vehicle_booking_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_booking',
            name='user_id',
        ),
    ]
