# Generated by Django 4.1.2 on 2022-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_remove_vehicle_booking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_booking',
            name='total_rate',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
