# Generated by Django 4.1.2 on 2022-10-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_vehicle_booking_total_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passenger_name', models.CharField(max_length=200)),
                ('Passenger_mobile', models.IntegerField(max_length=10)),
                ('Passenger_email', models.CharField(max_length=200)),
                ('adhar_number', models.CharField(max_length=200, null=True)),
                ('numberof_adult', models.IntegerField(max_length=200)),
                ('numberof_children', models.IntegerField(max_length=200)),
                ('total_rate', models.IntegerField(max_length=200, null=True)),
                ('Package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.package')),
            ],
        ),
    ]
