# Generated by Django 4.1.2 on 2022-11-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_package_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package_booking',
            name='numberof_adult',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package_booking',
            name='numberof_children',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking',
            name='numberof_seats',
            field=models.IntegerField(null=True),
        ),
    ]
