# Generated by Django 4.1.2 on 2022-11-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_alter_hotel_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_booking',
            name='Passenger_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking',
            name='Passenger_mobile',
            field=models.IntegerField(null=True),
        ),
    ]
