# Generated by Django 4.1.2 on 2022-11-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_alter_package_booking_total_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_holdername', models.CharField(max_length=20)),
                ('Card_number', models.IntegerField(null=True)),
                ('Valid_year', models.IntegerField(null=True)),
                ('Valid_month', models.CharField(max_length=20)),
                ('Total_amount', models.ImageField(null=True, upload_to='')),
                ('Busbooking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.vehicle_booking')),
                ('Vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.vehicle')),
            ],
        ),
    ]
