# Generated by Django 4.1.2 on 2022-11-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_payment_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_holdername', models.CharField(max_length=20)),
                ('Card_number', models.IntegerField(null=True)),
                ('Valid_year', models.IntegerField(null=True)),
                ('Valid_month', models.CharField(max_length=20)),
                ('Total_amount', models.ImageField(null=True, upload_to='')),
                ('Package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.package')),
                ('Packagebooking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.package_booking')),
            ],
        ),
    ]
