# Generated by Django 4.1.2 on 2022-11-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_payment_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_package',
            name='Total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
