# Generated by Django 4.1.2 on 2022-11-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_alter_payment_package_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_package',
            name='Package_id',
        ),
    ]
