# Generated by Django 4.1.2 on 2022-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_remove_payment_package_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_package',
            name='CVV',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
