# Generated by Django 4.1.2 on 2022-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_payment_package_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
