# Generated by Django 4.1.2 on 2022-11-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_hotel_available_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=200)),
                ('User_address', models.CharField(max_length=200)),
                ('User_mobile', models.IntegerField(null=True)),
                ('User_email', models.CharField(max_length=200)),
                ('User_adhar', models.IntegerField(null=True)),
                ('Check_in', models.DateField(null=True)),
                ('Check_out', models.DateField(null=True)),
                ('numberof_rooms', models.IntegerField(null=True)),
                ('numberof_adult', models.IntegerField(null=True)),
                ('numberof_children', models.IntegerField(null=True)),
                ('total_rate', models.IntegerField(null=True)),
                ('Hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hotel')),
            ],
        ),
    ]
