# Generated by Django 4.1.2 on 2022-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_hotel_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
