# Generated by Django 4.1.2 on 2022-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_package_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available_package',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment_package',
            name='CVV',
            field=models.IntegerField(null=True),
        ),
    ]
