# Generated by Django 4.1.2 on 2022-11-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_package_available_package_alter_payment_package_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='password2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
