# Generated by Django 4.1.2 on 2022-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='package',
            name='packagedetails',
            field=models.TextField(max_length=1000),
        ),
    ]
