# Generated by Django 4.1.2 on 2022-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_alter_hotel_description_alter_package_packagedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
