# Generated by Django 4.1.2 on 2022-11-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_vehicle_booking_pnr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_booking',
            name='PNR_H_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package_booking',
            name='PNR_P_id',
            field=models.IntegerField(null=True),
        ),
    ]
