# Generated by Django 4.1.2 on 2022-11-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_hotel_booking_pnr_h_id_package_booking_pnr_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_bus',
            name='CVV',
            field=models.IntegerField(null=True),
        ),
    ]
