# Generated by Django 4.1.2 on 2022-11-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_alter_vehicle_booking_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_booking',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.new_user'),
        ),
    ]
