# Generated by Django 4.1.2 on 2022-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_package_booking_current_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR_NUMBERS', models.IntegerField(null=True)),
                ('BOOKING_NUMBER', models.IntegerField(null=True)),
                ('Current_user_man', models.IntegerField(null=True)),
                ('email', models.IntegerField(null=True)),
                ('Mobile_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_booking',
            name='current_user',
            field=models.IntegerField(null=True),
        ),
    ]
