# Generated by Django 4.1.2 on 2022-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_cancelations_alter_vehicle_booking_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_booking',
            name='current_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
