# Generated by Django 4.1.2 on 2022-11-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_alter_cancelations_current_user_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelations',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
